export { default as ChatListPage } from './pages/ChatListPage'
export { default as ContactsPage } from './pages/ContactsPage'
export { default as ChatPage } from './pages/ChatPage'
export { default as MomentsPage } from './pages/MomentsPage'
export { default as ProfilePage } from './pages/ProfilePage'
export { default as LoginPage } from './pages/LoginPage'
export { default as RegisterPage } from './pages/RegisterPage'
